[versions]
neo-userdev = "7.0.173"
neo = "21.4.123"

[libraries]
neo = { group = "net.neoforged", name = "neoforge", version.ref = "neo" }

[plugins]
neo-userdev = { id = "net.neoforged.gradle.userdev", version.ref = "neo-userdev" }

[bundles]